apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/madfam-org/coupler-gateway
    newName: ghcr.io/madfam-org/coupler-gateway
    digest: sha256:b3b3f55e165f686c450aedc615d111b880e07db187bd040ed6b6b778962b957c
  - name: ghcr.io/madfam-org/coupler-landing
    newName: ghcr.io/madfam-org/coupler-landing
    digest: sha256:1984a8c8e0ff8e6a9c40596891a7bfb8e089a6e2e812c620d98840e60137ce57
