apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/madfam-org/coupler-gateway
    newName: ghcr.io/madfam-org/coupler-gateway
    digest: sha256:6626bc419147f01f7780f6a4d05327d9990520854dd3260747a9c7ba0f81ae6b
  - name: ghcr.io/madfam-org/coupler-landing
    newName: ghcr.io/madfam-org/coupler-landing
    digest: sha256:1bca8e4d9caf54db36075c01781bc4b6465f6f24c4111450eae09078902d84a5
