apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/madfam-org/coupler-gateway
    newName: ghcr.io/madfam-org/coupler-gateway
    digest: sha256:5da900087da969c504c0751d8ba14a21fd0bb27fd031eebe0ca2f349ef3c1683
  - name: ghcr.io/madfam-org/coupler-landing
    newName: ghcr.io/madfam-org/coupler-landing
    digest: sha256:0ce445f43a51c99b6decad30427ee12a5ec62b629290702466b9f53d87b21c46
